using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Game
{
    public class MapVariants
    {

        private static readonly string[] map1 = {
"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEFEEEEEEE",
"EEEEEEEEEEEEEEEEEEEEEEEEEGGGGGGEEEEEEE",
"EEEEEEEEEEEEEEEEEEEEEEGGEEEEEEEEEEEEEE",
"EEEEEEEEEEEEEEEEGEEGGEEEEEEEEEEEEEEEEE",
"EEEEEEEEEEEEEEGEEEEEEEEEEEEEEEEEEEEEEE",
"EEEEEEEEEEEEGEEEEEEEEEEEEEEEEEEEEEEEEE",
"EEEIEEEEEEEGGGEPEPEPEPEPEPEPEPEPEPEEEE",
"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG" };

        private static readonly string[] map2 = {
"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
"EEEIEEEEEEEEEEEEEEEEEFEEEEEEEPEEEEEEEE",
"GGGGGGGEPPPEEPPGGGGGGGGGGGGEEGGGEEEEGG",
"GGGGGGEEPPPPEEPEEEEEEEEEEEEEEEEEEEEGEG",
"GGGGGGEEPPPPPEPEEEEEEEEEEEEEEEEEEEEPEG",
"GGGGEEEPEEEEEEEEEEEEEEEEEEEEEPPPEEEEEG",
"GGGPEEEPEEEEPEPEEEEEEEEEEEEEEPPPEEEEEG",
"GGGPEEPEEEEEPEPEEEEEEEEEEEEEEPPPEEEEEG",
"GGGPEPEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GGGPEEEEEEEEEEEEEEEEEEEEEEEEEEEGEEEEEG",
"GEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEVEEG",
"GEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG", 
"GEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG", 
"GEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG", 
"GEEEEEEEPPPEEEEEEEPHEEEEEEEEVEEEEEEEEG",
"GEEEEEEEEEEEEEEEEhEPPPPEEEEEEEEEEEEEEG",
"GEEVEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPG" };

        private static readonly string[] map3 = {
"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
"EIEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEFE",
"GGGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEGGGG",
"GEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEX",
"GGGEPPEGEPPEGEPPEGEPPEGEPPEGEPPEEEEEEG",
"GEEEEEEPEEEEPEEEEPEEEEPEEEEPEEEVEGEEEG",
"GEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GEEHEEEEEEEEEEEEEEEEEhEEEHEEEEEEEEVEEG",
"GEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP" };

        private static readonly string[] map4 = {
"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"EEEEGPEEEEEEEEEKEEEEEKEEEEEKEEEEEKEEEG",
"EIEEGPEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GGEEGGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEFG",
"GGGEEGEEEEEELEEEEELEEEEELEEEEELEEEEEGG",
"GGEEGGEEGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"GGGEEGGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GGEEGGGGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GGGEEGGGGGGGEEEEEEEEEhEEEHEEEEEEEEEEEG",
"GGEEGGEEEEEEEEEEEEEEEEEPEEEEEEEEEEEEGG",
"GGGEEGEEEGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"GGEEGGGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GGGEEGGGZEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GGEEGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEEEG",
"GGGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEGG",
"GGGLGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEXGGG",
"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG" };
        private static readonly string[] map5 = {
"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
"GGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GGEEEEEGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GGEEEEEGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GGEEEEEGPPPPPPEPPPPPPPPPPPPPPPPPPPPPPG",
"GGPPPPEGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GEEEEEEGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GEEEEEEGPPPPPPPGPPPGPPGPPGPPGPPGPPGEPG",
"GGEEEVEGEEEEEEEEEEEEEEEEEEEEEEEEEEEEXG",
"GGEEEEEGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GGPPEPPGZEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GEEEEEEGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GIEEEEEGFEEESEEEBEEEESEEEEBEEEESEEEEEG",
"GGEEEEEGGEEGGEEEGGEEEGGEEEGGEEEGGEEEGG",
"GGEEVEEGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEG",
"GGPPPPPGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPG" };

        public static string[] GetMap(int Level,int TotalNumberOfLevels)
        {
            switch (Level % TotalNumberOfLevels)
            {
                case 1:
                    return map1;
                case 2:
                    return map2;
                case 3:
                    return map3;
                case 4:
                    return map4;
                case 0:
                    return map5;
            }
            return map1;
        }
    }

}
